import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, BarChart3, Building2, CreditCard, KeyRound, LoaderCircle, LogIn, Pencil, RefreshCw, ShieldAlert, ShieldCheck, TestTube2, Users } from 'lucide-react';
import { isSupabaseConfigured, supabase } from '../../lib/supabase';
import { commercialTrialService, PlatformOverview, PlatformUser } from '../../services/commercialTrialService';

type Tab = 'overview' | 'trials' | 'companies' | 'users' | 'engagement' | 'modules' | 'risk' | 'billing';
type TenantModule = {tenant_id:string;module_code:string;enabled:boolean;source:string};
const moduleNames:Record<string,string>={SAC:'SAC básico',QUALITY:'Qualidade',TRACEABILITY:'Lotes e rastreabilidade',RISK:'Gestão de riscos',CAPA:'CAPA / 5W2H',REGULATORY:'Regulatório',AUDIT_OCP:'Auditoria OCP'};
const engagement = { total_sessions: 0, total_area_views: 0, total_record_events: 0, active_users_7d: 0, active_users_30d: 0, areas: [] };
const empty: PlatformOverview = { trials: [], subscriptions: [], orders: [], alerts: [], users: [], engagement, risks: [] };
const roles = ['ADMIN_EMPRESA', 'DIRETORIA', 'RESPONSAVEL_TECNICA', 'SAC', 'TECNICO', 'LOGISTICA', 'GERENTE_LOJA'];
const areaNames: Record<string,string> = { dashboard:'Dashboard',tickets:'Chamados',quality:'Qualidade',technical:'Serviço técnico',logistics:'Logística',reports:'Relatórios',traceability:'Lotes e rastreabilidade',users:'Usuários',settings:'Configurações',audit:'Auditoria',knowledge:'Base de conhecimento',import:'Importação' };

export function PlatformAdmin() {
  const [authenticated,setAuthenticated]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[data,setData]=useState<PlatformOverview>(empty),[tab,setTab]=useState<Tab>('overview'),[loading,setLoading]=useState(false),[error,setError]=useState('');
  const [query,setQuery]=useState(''),[tenantFilter,setTenantFilter]=useState(''),[statusFilter,setStatusFilter]=useState('');
  const [tenantModules,setTenantModules]=useState<TenantModule[]>([]);
  const load=async()=>{setLoading(true);setError('');try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Sessão administrativa inválida.');const{data:profile,error:profileError}=await supabase.from('profiles').select('role_code,is_active').eq('id',user.id).single();if(profileError||!profile?.is_active||profile.role_code!=='SUPERADMIN'){await supabase.auth.signOut();throw new Error('A Central Gerencial é exclusiva para o SUPERADMIN da GRIT.');}const[overview,moduleResult]=await Promise.all([commercialTrialService.platformOverview(),supabase.from('tenant_modules').select('tenant_id,module_code,enabled,source')]);if(moduleResult.error)throw moduleResult.error;setData(overview);setTenantModules((moduleResult.data||[]) as TenantModule[]);setAuthenticated(true);}catch(cause){setAuthenticated(false);setError(cause instanceof Error?cause.message:'Não foi possível carregar a gestão da plataforma.');}finally{setLoading(false);}};
  useEffect(()=>{if(isSupabaseConfigured)supabase.auth.getSession().then(({data:session})=>{if(session.session)load();});},[]);
  const login=async(event:FormEvent)=>{event.preventDefault();if(!isSupabaseConfigured)return;setLoading(true);setError('');const{error:authError}=await supabase.auth.signInWithPassword({email,password});if(authError){setError('E-mail ou senha inválidos.');setLoading(false);return;}await load();};

  const metrics=useMemo(()=>({leads:data.trials.length,trials:data.subscriptions.filter(item=>item.status==='TRIAL').length,active:data.subscriptions.filter(item=>item.status==='ACTIVE').length,users:data.users.filter(item=>item.is_active).length,alerts:data.alerts.length,revenue:data.orders.filter(item=>item.status==='PAID').reduce((sum,item)=>sum+Number(item.expected_amount||0),0)}),[data]);
  const tenantOptions=useMemo(()=>Array.from(new Map(data.subscriptions.map(item=>[item.tenant_id,item.tenant.trade_name||item.tenant.name])).entries()),[data.subscriptions]);
  const normalized=query.trim().toLowerCase();
  const visibleUsers=useMemo(()=>data.users.filter(item=>(!tenantFilter||item.tenant_id===tenantFilter)&&(!statusFilter||(statusFilter==='ACTIVE'?item.is_active:!item.is_active))&&(!normalized||`${item.full_name} ${item.email} ${item.role_code} ${item.tenant?.name||''} ${item.tenant?.trade_name||''}`.toLowerCase().includes(normalized))),[data.users,tenantFilter,statusFilter,normalized]);
  const visibleCompanies=useMemo(()=>data.subscriptions.filter(item=>(!tenantFilter||item.tenant_id===tenantFilter)&&(!statusFilter||item.status===statusFilter)&&(!normalized||`${item.tenant.name} ${item.tenant.trade_name||''} ${item.tenant.document} ${item.billing_email||''}`.toLowerCase().includes(normalized))),[data.subscriptions,tenantFilter,statusFilter,normalized]);

  const updateUser=async(user:PlatformUser,changes:Partial<PlatformUser>)=>{const roleCode=changes.role_code||user.role_code,isActive=changes.is_active??user.is_active;if(!window.confirm(`Confirma a alteração de acesso de ${user.full_name}?`))return;setLoading(true);setError('');try{const updated=await commercialTrialService.updatePlatformUser(user.id,roleCode,isActive);setData(old=>({...old,users:old.users.map(item=>item.id===user.id?{...item,...updated}:item)}));}catch(cause){setError(cause instanceof Error?cause.message:'Falha ao atualizar usuário.');}finally{setLoading(false);}};
  const editUser=async(user:PlatformUser)=>{const fullName=window.prompt('Nome completo:',user.full_name)?.trim();if(!fullName)return;const targetEmail=window.prompt('E-mail cadastrado:',user.email)?.trim().toLowerCase();if(!targetEmail)return;const roleCode=window.prompt(`Perfil:\n${roles.join(', ')}`,user.role_code)?.trim().toUpperCase();if(!roleCode||!roles.includes(roleCode)){setError('Perfil de acesso inválido.');return;}if(!window.confirm(`Salvar as alterações de ${fullName}?`))return;setLoading(true);setError('');try{const updated=await commercialTrialService.editPlatformUser(user.id,fullName,targetEmail,roleCode,user.is_active);setData(old=>({...old,users:old.users.map(item=>item.id===user.id?{...item,...updated}:item)}));}catch(cause){setError(cause instanceof Error?cause.message:'Falha ao editar usuário.');}finally{setLoading(false);}};
  const recover=async(user:PlatformUser)=>{if(!window.confirm(`Enviar e-mail de recuperação para ${user.email}?`))return;setLoading(true);setError('');try{await commercialTrialService.sendPasswordRecovery(user.id);window.alert(`Recuperação enviada para ${user.email}.`);}catch(cause){setError(cause instanceof Error?cause.message:'Falha ao enviar recuperação.');}finally{setLoading(false);}};
  const updateSubscription=async(id:string,status:'ACTIVE'|'SUSPENDED'|'CANCELED')=>{const reason=window.prompt(`Justificativa para alterar a assinatura para ${status}:`,'');if(!reason)return;if(reason.trim().length<10){setError('A justificativa deve ter pelo menos 10 caracteres.');return;}setLoading(true);try{await commercialTrialService.updateSubscription(id,status,reason.trim());await load();}catch(cause){setError(cause instanceof Error?cause.message:'Falha ao atualizar assinatura.');}finally{setLoading(false);}};
  const acknowledge=async(id:string)=>{setLoading(true);try{await commercialTrialService.acknowledgeAlert(id);setData(old=>({...old,alerts:old.alerts.filter(item=>item.id!==id)}));}catch(cause){setError(cause instanceof Error?cause.message:'Falha ao tratar alerta.');}finally{setLoading(false);}};
  const toggleModule=async(tenantId:string,moduleCode:string,enabled:boolean)=>{if(moduleCode==='SAC'&&!enabled){setError('O SAC é a base do contrato e não pode ser desativado.');return;}if(!window.confirm(`${enabled?'Ativar':'Desativar'} ${moduleNames[moduleCode]} para esta empresa?`))return;setLoading(true);setError('');try{const{error:moduleError}=await supabase.from('tenant_modules').upsert({tenant_id:tenantId,module_code:moduleCode,enabled,source:'OVERRIDE',updated_at:new Date().toISOString()},{onConflict:'tenant_id,module_code'});if(moduleError)throw moduleError;setTenantModules(current=>[...current.filter(item=>!(item.tenant_id===tenantId&&item.module_code===moduleCode)),{tenant_id:tenantId,module_code:moduleCode,enabled,source:'OVERRIDE'}]);}catch(cause){setError(cause instanceof Error?cause.message:'Falha ao atualizar os módulos do contrato.');}finally{setLoading(false);}};
  const logout=async()=>{await supabase.auth.signOut();setAuthenticated(false);setData(empty);setPassword('');};

  if(!authenticated)return <main className="grid min-h-screen place-items-center bg-slate-950 p-5 text-white"><form onSubmit={login} className="w-full max-w-md rounded-3xl border border-white/10 bg-slate-900 p-8"><ShieldCheck className="text-orange-300"/><h1 className="mt-4 text-2xl font-black">Gestão da plataforma</h1><p className="mt-2 text-sm text-slate-400">Use o mesmo superadministrador do SACPROH.</p>{!isSupabaseConfigured&&<p className="mt-4 rounded-xl bg-amber-400/10 p-3 text-sm text-amber-200">A publicação ainda não recebeu as credenciais do Supabase.</p>}<input required type="email" placeholder="E-mail" value={email} onChange={event=>setEmail(event.target.value)} className={field}/><input required type="password" placeholder="Senha" value={password} onChange={event=>setPassword(event.target.value)} className={field}/><button disabled={loading||!isSupabaseConfigured} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-[#FF8500] p-3 font-black disabled:opacity-50"><LogIn size={18}/>Entrar</button>{error&&<p className="mt-4 rounded-xl bg-red-400/10 p-3 text-sm text-red-300">{error}</p>}</form></main>;

  const cards=[[TestTube2,'Leads',metrics.leads],[Building2,'Trials ativos',metrics.trials],[ShieldCheck,'Assinaturas ativas',metrics.active],[Users,'Usuários ativos',metrics.users],[Activity,'Ativos em 7 dias',data.engagement.active_users_7d],[CreditCard,'Recebido',`R$ ${metrics.revenue.toLocaleString('pt-BR',{minimumFractionDigits:2})}`]] as const;
  return <main className="min-h-screen bg-slate-950 p-4 text-white md:p-8"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-bold text-orange-300">GRIT · SUPERADMIN</p><h1 className="text-3xl font-black">Central gerencial SAC 4.0</h1><p className="text-sm text-slate-400">Empresas, usuários, acessos, engajamento, assinaturas e pagamentos.</p></div><div className="flex gap-2"><button onClick={load} disabled={loading} className="flex items-center gap-2 rounded-xl border border-white/15 px-4 py-2"><RefreshCw size={17}/>Atualizar</button><button onClick={logout} className="rounded-xl border border-white/15 px-4 py-2">Sair</button></div></header>{error&&<p className="mt-5 rounded-xl bg-red-400/10 p-3 text-red-300">{error}</p>}{loading&&<p className="mt-4 flex items-center gap-2 text-orange-300"><LoaderCircle className="animate-spin" size={18}/>Processando...</p>}
    <nav className="mt-7 flex gap-2 overflow-x-auto">{([['overview','Visão geral'],['trials','Leads e testes'],['companies','Empresas'],['users','Usuários'],['engagement','Engajamento'],['modules','Módulos por contrato'],['risk','Riscos e conformidade'],['billing','Pagamentos']] as [Tab,string][]).map(([key,label])=><button key={key} onClick={()=>{setTab(key);setStatusFilter('');}} className={`whitespace-nowrap rounded-xl px-4 py-2 text-sm font-bold ${tab===key?'bg-orange-400 text-slate-950':'bg-slate-900 text-slate-300'}`}>{label}</button>)}</nav>
    {['companies','users'].includes(tab)&&<section className="mt-5 grid gap-3 rounded-2xl border border-white/10 bg-slate-900 p-4 md:grid-cols-3"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar empresa, usuário, e-mail ou CNPJ" className={filter}/><select value={tenantFilter} onChange={e=>setTenantFilter(e.target.value)} className={filter}><option value="">Todas as empresas</option>{tenantOptions.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} className={filter}><option value="">Todos os status</option>{tab==='users'?<><option value="ACTIVE">Ativos</option><option value="BLOCKED">Bloqueados</option></>:<><option value="TRIAL">Trial</option><option value="ACTIVE">Ativa</option><option value="SUSPENDED">Suspensa</option><option value="CANCELED">Cancelada</option></>}</select></section>}
    {tab==='overview'&&<div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{cards.map(([Icon,label,value])=><article key={label} className={card}><Icon className="text-orange-300"/><p className="mt-4 text-sm text-slate-400">{label}</p><strong className="text-3xl">{value}</strong></article>)}</div>}
    {tab==='trials'&&<section className="mt-6 space-y-3">{data.trials.length===0&&<Empty label="Nenhum lead ou teste cadastrado."/>}{data.trials.map(item=><article key={item.id} className={card}><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-black">{item.company_name}</h2><p className="text-sm text-slate-300">{item.work_email} · {item.segment}</p></div><Badge>{item.status}</Badge></div><p className="mt-2 text-xs text-slate-400">Entrada: {dateTime(item.created_at)}{item.trial_ends_at&&` · Trial até ${date(item.trial_ends_at)}`}</p></article>)}</section>}
    {tab==='companies'&&<section className="mt-6 space-y-3">{visibleCompanies.length===0&&<Empty label="Nenhuma empresa encontrada."/>}{visibleCompanies.map(item=><article key={item.id} className={card}><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-black">{item.tenant.trade_name||item.tenant.name}</h2><p className="text-sm text-slate-300">CNPJ {item.tenant.document} · {item.plan.name} · limite {item.seat_limit||item.plan.included_seats}</p></div><Badge>{item.status}</Badge></div><div className="mt-4 flex flex-wrap gap-2">{item.status!=='ACTIVE'&&<Action color="emerald" onClick={()=>updateSubscription(item.id,'ACTIVE')}>Ativar</Action>}{item.status!=='SUSPENDED'&&<Action color="amber" onClick={()=>updateSubscription(item.id,'SUSPENDED')}>Suspender</Action>}{item.status!=='CANCELED'&&<Action color="red" onClick={()=>updateSubscription(item.id,'CANCELED')}>Cancelar</Action>}</div></article>)}</section>}
    {tab==='users'&&<section className="mt-6 overflow-x-auto rounded-2xl border border-white/10 bg-slate-900"><table className="w-full min-w-[1150px] text-left text-sm"><thead className="bg-slate-800 text-slate-300"><tr>{['Usuário','Empresa','Perfil','Status','Último acesso','Uso em 30 dias','Área principal','Ações'].map(label=><th key={label} className="p-4">{label}</th>)}</tr></thead><tbody>{visibleUsers.map(user=><tr key={user.id} className="border-t border-white/10"><td className="p-4"><strong>{user.full_name}</strong><p className="text-xs text-slate-400">{user.email}</p></td><td className="p-4">{user.tenant?.trade_name||user.tenant?.name||'—'}</td><td className="p-4">{user.role_code}</td><td className="p-4">{user.is_active?'Ativo':'Bloqueado'}</td><td className="p-4">{user.last_sign_in_at?dateTime(user.last_sign_in_at):'Sem acesso'}</td><td className="p-4"><strong>{user.area_views||0}</strong> áreas · {user.record_events||0} registros</td><td className="p-4">{areaNames[user.top_area||'']||user.top_area||'—'}</td><td className="p-4"><div className="flex gap-2">{user.role_code!=='SUPERADMIN'&&<><button title="Editar usuário" onClick={()=>editUser(user)} className={iconButton}><Pencil size={16}/></button><button title="Enviar recuperação de senha" onClick={()=>recover(user)} className={iconButton}><KeyRound size={16}/></button><Action color={user.is_active?'red':'emerald'} onClick={()=>updateUser(user,{is_active:!user.is_active})}>{user.is_active?'Bloquear':'Reativar'}</Action></>}</div></td></tr>)}</tbody></table></section>}
    {tab==='engagement'&&<section className="mt-6"><div className="grid gap-4 md:grid-cols-4">{[[Activity,'Usuários ativos 7d',data.engagement.active_users_7d],[Users,'Usuários ativos 30d',data.engagement.active_users_30d],[BarChart3,'Acessos às áreas',data.engagement.total_area_views],[Pencil,'Registros movimentados',data.engagement.total_record_events]].map(([Icon,label,value]:any)=><article key={label} className={card}><Icon className="text-cyan-300"/><p className="mt-3 text-sm text-slate-400">{label}</p><strong className="text-3xl">{value}</strong></article>)}</div><div className={`${card} mt-5`}><h2 className="font-black">Áreas mais acessadas nos últimos 30 dias</h2><div className="mt-5 space-y-3">{data.engagement.areas.length===0&&<p className="text-sm text-slate-400">A medição começará com os próximos acessos ao SAC.</p>}{data.engagement.areas.map(item=><div key={item.area} className="grid grid-cols-[1fr_auto_auto] gap-4 border-b border-white/10 pb-3"><span>{areaNames[item.area]||item.area}</span><strong>{item.views} acessos</strong><span className="text-slate-400">{item.users} usuários</span></div>)}</div></div></section>}
    {tab==='modules'&&<section className="mt-6 space-y-4"><div><h2 className="text-xl font-black">Módulos habilitados por contrato</h2><p className="text-sm text-slate-400">O plano básico mantém somente o SAC. Recursos adicionais podem ser ativados por empresa conforme a contratação.</p></div>{data.subscriptions.map(subscription=><article key={subscription.tenant_id} className={card}><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-black">{subscription.tenant.trade_name||subscription.tenant.name}</h3><p className="text-xs text-slate-400">{subscription.plan.name} · alteração SUPERADMIN</p></div><Badge>{subscription.status}</Badge></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(moduleNames).map(([code,label])=>{const row=tenantModules.find(item=>item.tenant_id===subscription.tenant_id&&item.module_code===code);const active=code==='SAC'||Boolean(row?.enabled);return <label key={code} className={`flex items-center justify-between rounded-xl border p-3 text-sm ${active?'border-emerald-300/30 bg-emerald-400/10':'border-white/10 bg-slate-950'}`}><span><b>{label}</b><small className="block text-slate-400">{row?.source||'PLANO'}</small></span><input type="checkbox" checked={active} disabled={code==='SAC'||loading} onChange={event=>void toggleModule(subscription.tenant_id,code,event.target.checked)} className="h-5 w-5"/></label>;})}</div></article>)}</section>}
    {tab==='risk'&&<section className="mt-6 space-y-3"><h2 className="flex items-center gap-2 text-xl font-black"><ShieldAlert className="text-orange-300"/>Governança de risco por empresa</h2><p className="text-sm text-slate-400">Priorização para o SUPERADMIN; a decisão regulatória permanece com a RT.</p>{data.risks.length===0&&<Empty label="Nenhum registro de risco consolidado."/>}{data.risks.map(item=>{const company=data.subscriptions.find(s=>s.tenant_id===item.tenant_id)?.tenant;return <article key={item.tenant_id} className={card}><div className="flex justify-between gap-3"><div><h3 className="font-black">{company?.trade_name||company?.name||item.tenant_id}</h3><p className="text-xs text-slate-400">{item.units_sold.toLocaleString('pt-BR')} unidades · {item.occurrences_ppm.toLocaleString('pt-BR')} ocorrências/milhão</p></div><Badge>{item.critical_risks?'ATENÇÃO':'MONITORADO'}</Badge></div><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4">{[['Riscos abertos',item.open_risks],['Críticos',item.critical_risks],['Notificações',item.pending_notifications],['CAPA vencidas',item.overdue_actions]].map(([label,value])=><div key={label}><strong className="text-2xl">{value}</strong><p className="text-xs text-slate-400">{label}</p></div>)}</div></article>;})}</section>}
    {tab==='billing'&&<section className="mt-6 grid gap-4 lg:grid-cols-2"><div><h2 className="mb-3 flex gap-2 font-black"><CreditCard/>Pedidos Mercado Pago</h2>{data.orders.length===0&&<Empty label="Nenhum pedido registrado."/>}{data.orders.map(order=><article key={order.id} className={`${card} mb-3`}><div className="flex justify-between"><strong>{order.plan_code}</strong><span>{order.status}</span></div><p className="mt-2 text-sm text-slate-300">R$ {Number(order.expected_amount).toLocaleString('pt-BR',{minimumFractionDigits:2})} · {order.last_payment_status||'sem retorno'}</p></article>)}</div><div><h2 className="mb-3 flex gap-2 font-black"><AlertTriangle/>Alertas</h2>{data.alerts.length===0&&<Empty label="Nenhum alerta aberto."/>}{data.alerts.map(alert=><article key={alert.id} className="mb-3 rounded-2xl border border-red-300/20 bg-red-400/10 p-5"><strong>{alert.alert_type}</strong><p className="mt-2 text-sm">{alert.message}</p><button onClick={()=>acknowledge(alert.id)} className="mt-3 rounded-lg border border-red-200/30 px-3 py-2 text-xs font-bold">Marcar como tratado</button></article>)}</div></section>}
  </div></main>;
}

const field='mt-3 w-full rounded-xl border border-white/15 bg-slate-950 p-3 text-white',filter='rounded-xl border border-white/10 bg-slate-950 p-3 text-sm',card='rounded-2xl border border-white/10 bg-slate-900 p-5',iconButton='rounded-lg border border-white/15 p-2 text-slate-200 hover:bg-white/10';
const date=(value:string)=>new Date(value).toLocaleDateString('pt-BR'),dateTime=(value:string)=>new Date(value).toLocaleString('pt-BR');
function Empty({label}:{label:string}){return <p className="rounded-2xl border border-dashed border-white/15 bg-slate-900 p-6 text-sm text-slate-400">{label}</p>;} function Badge({children}:{children:string}){return <span className="h-fit rounded-full bg-cyan-300 px-3 py-1 text-xs font-black text-slate-950">{children}</span>;} function Action({children,color,onClick}:{children:string;color:'emerald'|'amber'|'red';onClick:()=>void}){const styles={emerald:'bg-emerald-300',amber:'bg-amber-300',red:'bg-red-300'};return <button onClick={onClick} className={`rounded-lg px-3 py-2 text-xs font-black text-slate-950 ${styles[color]}`}>{children}</button>;}
