import { useEffect,useMemo,useState } from 'react';
import { AlertTriangle,BookOpenCheck,FileCheck2,Printer,Save,ShieldCheck } from 'lucide-react';
import { Product,Tenant,Ticket,UserProfile } from '../../types';
import { ProductCompliance,regulatoryService } from '../../services/regulatoryService';

type Props={tenant:Tenant;currentUser:UserProfile;tickets:Ticket[];products:Product[]};
const today=new Date().toISOString().slice(0,10),yearStart=`${new Date().getFullYear()}-01-01`;
export function RegulatoryReports({tenant,currentUser,tickets,products}:Props){
  const isSuperAdmin=currentUser.roleCode==='SUPERADMIN',canAccessRegulatory=isSuperAdmin||currentUser.roleCode==='RESPONSAVEL_TECNICA';
  const[type,setType]=useState<'ANVISA'|'INMETRO'>('ANVISA'),[start,setStart]=useState(yearStart),[end,setEnd]=useState(today),[items,setItems]=useState<ProductCompliance[]>([]),[editing,setEditing]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(false);
  useEffect(()=>{regulatoryService.listCompliance().then(setItems).catch(()=>setMessage('Não foi possível carregar a conformidade regulatória.'));},[]);
  const periodTickets=useMemo(()=>tickets.filter(t=>t.createdAt.slice(0,10)>=start&&t.createdAt.slice(0,10)<=end),[tickets,start,end]);
  const stats=useMemo(()=>{const adverse=periodTickets.filter(t=>t.adverseEventFlag),risk=periodTickets.filter(t=>t.userRiskFlag),damage=periodTickets.filter(t=>t.damageFlag),closed=periodTickets.filter(t=>t.status.startsWith('CLOSED')),lots=new Set(periodTickets.flatMap(t=>t.items.map(i=>i.lotNumber).filter(Boolean))),serials=new Set(periodTickets.flatMap(t=>t.items.map(i=>i.serialNumber).filter(Boolean)));return{total:periodTickets.length,adverse:adverse.length,risk:risk.length,damage:damage.length,closed:closed.length,open:periodTickets.length-closed.length,lots:lots.size,serials:serials.size,anvisaCovered:products.filter(p=>p.anvisaRegister||items.find(i=>i.productId===p.id)?.anvisaRegistration).length,inmetroRequired:items.filter(i=>i.inmetroRequired).length,inmetroValid:items.filter(i=>i.inmetroRequired&&i.certificateNumber&&(!i.certificateExpiration||i.certificateExpiration>=today)).length};},[periodTickets,products,items]);
  const saveSnapshot=async()=>{setLoading(true);setMessage('');try{await regulatoryService.saveSnapshot({tenantId:tenant.id,type,start,end,title:`Relatório ${type} ${start} a ${end}`,summary:stats,userId:currentUser.id});setMessage('Relatório salvo no histórico regulatório.');}catch{setMessage('Falha ao salvar. Confirme o perfil de Responsável Técnico.');}finally{setLoading(false);}};
  const saveProduct=async(product:Product,item:ProductCompliance)=>{setLoading(true);try{const saved=await regulatoryService.saveCompliance(item,currentUser.id);setItems(old=>[...old.filter(x=>x.productId!==product.id),saved]);setEditing('');setMessage('Conformidade do produto atualizada.');}catch{setMessage('Falha ao salvar conformidade regulatória.');}finally{setLoading(false);}};
  if(!canAccessRegulatory)return <div className="rounded-xl border border-red-200 bg-red-50 p-6 text-red-800"><ShieldCheck/><h1 className="mt-3 text-xl font-black">Acesso regulatório restrito</h1><p className="mt-2 text-sm">Este módulo está disponível somente para o Responsável Técnico e o Superadministrador.</p></div>;
  return <section className="space-y-5 print:bg-white"><header className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black uppercase text-[#145EDB]">Área regulatória exclusiva</p><h1 className="text-2xl font-black">Relatórios Anvisa e Inmetro</h1><p className="text-xs text-slate-500">{tenant.tradeName||tenant.name} · RT: {currentUser.fullName}</p></div><div className="flex gap-2 print:hidden"><button onClick={saveSnapshot} disabled={loading} className="flex items-center gap-2 rounded-lg bg-[#145EDB] px-4 py-2 text-xs font-black text-white"><Save size={16}/>Salvar histórico</button><button onClick={()=>window.print()} className="flex items-center gap-2 rounded-lg border px-4 py-2 text-xs font-black"><Printer size={16}/>Imprimir / PDF</button></div></header>
    {isSuperAdmin&&<div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900"><strong>Modo de supervisão administrativa.</strong> Você pode auditar e corrigir os registros; toda alteração permanece vinculada ao seu usuário no LOG. A validação e o envio regulatório oficial continuam sob responsabilidade da RT.</div>}
    {message&&<p className="rounded-lg bg-blue-50 p-3 text-xs font-bold text-blue-800">{message}</p>}
    <div className="flex flex-wrap gap-2 print:hidden"><button onClick={()=>setType('ANVISA')} className={tab(type==='ANVISA')}>Resumo Anvisa</button><button onClick={()=>setType('INMETRO')} className={tab(type==='INMETRO')}>Conformidade Inmetro</button><label className="ml-auto text-xs font-bold">Início<input type="date" value={start} onChange={e=>setStart(e.target.value)} className="ml-2 rounded border p-2"/></label><label className="text-xs font-bold">Fim<input type="date" value={end} onChange={e=>setEnd(e.target.value)} className="ml-2 rounded border p-2"/></label></div>
    <article className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><FileCheck2 className="text-[#145EDB]"/><div><h2 className="font-black">{type==='ANVISA'?'Resumo de tecnovigilância e pós-mercado':'Resumo de avaliação da conformidade'}</h2><p className="text-xs text-slate-500">Período: {date(start)} a {date(end)} · Emitido em {new Date().toLocaleString('pt-BR')}</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{(type==='ANVISA'?[[stats.total,'Queixas e atendimentos'],[stats.adverse,'Eventos adversos'],[stats.risk,'Ocorrências com risco'],[stats.damage,'Ocorrências com dano'],[stats.open,'Investigações abertas'],[stats.closed,'Concluídas'],[stats.lots,'Lotes rastreados'],[stats.anvisaCovered,'Produtos com regularização']]:[[products.length,'Produtos avaliados'],[stats.inmetroRequired,'Certificação obrigatória'],[stats.inmetroValid,'Certificados válidos'],[Math.max(stats.inmetroRequired-stats.inmetroValid,0),'Pendências críticas']]).map(([value,label])=><div key={String(label)} className="rounded-lg bg-slate-50 p-4"><strong className="text-2xl text-[#145EDB]">{value}</strong><p className="text-xs font-bold text-slate-600">{label}</p></div>)}</div>
      {type==='ANVISA'&&<div className="mt-5 grid gap-4 lg:grid-cols-2"><Info title="Escopo do acompanhamento" lines={['Queixas técnicas e eventos adversos','Lote, série, UDI e regularização','Investigação, causa e conclusão','Ações de campo, alertas e recall']}/><Info title="Pendências para revisão do RT" lines={[`${stats.open} ocorrência(s) ainda aberta(s)`,`${periodTickets.filter(t=>t.adverseEventFlag&&!t.finalOpinion).length} evento(s) adverso(s) sem parecer final`,`${periodTickets.filter(t=>t.items.some(i=>!i.lotNumber&&!i.serialNumber)).length} chamado(s) sem lote ou série`,`Confirmar notificabilidade e prazos no Notivisa/Solicita`]}/></div>}
    </article>
    <article className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 font-black"><BookOpenCheck className="text-emerald-600"/>Cadastro regulatório por produto</h2><p className="mt-1 text-xs text-slate-500">O relatório evidencia lacunas; não substitui protocolo oficial, análise do RT ou validação do escopo compulsório.</p><div className="mt-4 space-y-3">{products.map(product=>{const current=items.find(i=>i.productId===product.id)||{productId:product.id,tenantId:tenant.id,inmetroRequired:false,anvisaRegistration:product.anvisaRegister||''};return <ProductRow key={product.id} product={product} item={current} editing={editing===product.id} onEdit={()=>setEditing(product.id)} onCancel={()=>setEditing('')} onSave={value=>saveProduct(product,value)}/>;})}</div></article>
    <footer className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs text-amber-900"><AlertTriangle className="inline h-4 w-4"/> Documento de apoio gerencial. Antes do envio, o Responsável Técnico deve revisar dados, classificação, prazos, evidências e utilizar os sistemas oficiais aplicáveis.</footer>
  </section>;
}
function ProductRow({product,item,editing,onEdit,onCancel,onSave}:{key?:string;product:Product;item:ProductCompliance;editing:boolean;onEdit:()=>void;onCancel:()=>void;onSave:(v:ProductCompliance)=>Promise<void>}){const[value,setValue]=useState(item);useEffect(()=>setValue(item),[item]);if(!editing)return <div className="grid gap-2 rounded-lg border p-3 text-xs md:grid-cols-[1.4fr_1fr_1fr_auto]"><div><strong>{product.name}</strong><p className="text-slate-500">{product.model||product.codeSku}</p></div><span>Anvisa: {item.anvisaRegistration||'PENDENTE'}</span><span>Inmetro: {!item.inmetroRequired?'Não marcado':item.certificateNumber||'PENDENTE'}</span><button onClick={onEdit} className="font-black text-[#145EDB] print:hidden">Revisar</button></div>;return <div className="grid gap-2 rounded-lg border border-blue-200 bg-blue-50 p-3 text-xs md:grid-cols-3"><strong className="md:col-span-3">{product.name}</strong><input placeholder="Registro Anvisa" value={value.anvisaRegistration||''} onChange={e=>setValue({...value,anvisaRegistration:e.target.value})} className="rounded border p-2"/><input placeholder="UDI-DI" value={value.udiDi||''} onChange={e=>setValue({...value,udiDi:e.target.value})} className="rounded border p-2"/><label className="flex items-center gap-2 rounded border bg-white p-2"><input type="checkbox" checked={value.inmetroRequired} onChange={e=>setValue({...value,inmetroRequired:e.target.checked})}/>Exige Inmetro</label><input placeholder="Registro Inmetro" value={value.inmetroRegistration||''} onChange={e=>setValue({...value,inmetroRegistration:e.target.value})} className="rounded border p-2"/><input placeholder="Certificado / OCP" value={value.certificateNumber||''} onChange={e=>setValue({...value,certificateNumber:e.target.value})} className="rounded border p-2"/><input type="date" title="Validade do certificado" value={value.certificateExpiration||''} onChange={e=>setValue({...value,certificateExpiration:e.target.value})} className="rounded border p-2"/><div className="md:col-span-3 flex justify-end gap-2"><button onClick={onCancel} className="rounded border px-3 py-2">Cancelar</button><button onClick={()=>onSave(value)} className="rounded bg-[#145EDB] px-3 py-2 font-black text-white">Salvar</button></div></div>}
function Info({title,lines}:{title:string;lines:string[]}){return <div className="rounded-lg border p-4"><h3 className="font-black">{title}</h3><ul className="mt-2 space-y-1 text-xs text-slate-600">{lines.map(line=><li key={line}>• {line}</li>)}</ul></div>}const tab=(active:boolean)=>`rounded-lg px-4 py-2 text-xs font-black ${active?'bg-[#145EDB] text-white':'border bg-white'}`,date=(v:string)=>new Date(`${v}T12:00:00`).toLocaleDateString('pt-BR');
